apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  namespace: moleprowithdb
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
     labels:
        app: {{ .Values.appname }}
    spec:
      initContainers:
        - name: initcontainer
          image: alpine
          command:
            - sh
            - /scripts/download_data.sh
          env:
            - name: DB_DATA_URL
              value: {{ .Values.dataurlis }}
          volumeMounts:
            - name: {{ .Values.appname }}
              mountPath: /usr/src/app/data
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["nohup","gunicorn", "-w","2","-b","0.0.0.0:8080","openapi_server.__main__:app","--timeout","1800"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: {{ .Values.appname }}
              mountPath: /usr/src/app/data
      volumes:
        - name: {{ .Values.appname }}
          persistentVolumeClaim:
            claimName: {{ .Values.appname }}
      restartPolicy: Always