openapi: 3.0.1
info:
  contact:
    email: translator@broadinstitute.org
  description: Molecular Data Provider for NCATS Biomedical Translator Reasoners
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: '{{url}}'
  title: Systems Molecular Data Provider for NCATS Biomedical Translator Reasoners
  version: 0.9.2
externalDocs:
  description: Documentation for the NCATS Biomedical Translator Reasoners web services
  url: https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI
servers:
- url: /
tags:
- description: Get supported relationships by source and target
  externalDocs:
    description: Documentation for the reasoner predicates function
    url: http://reasonerhost.ncats.io/overview.html#predicates
  name: predicates
- description: Query reasoner using a predefined question type
  externalDocs:
    description: Documentation for the reasoner query function
    url: http://reasonerhost.ncats.io/overview.html#query
  name: query
paths:
  /predicates:
    get:
      operationId: predicates_get
      responses:
        200:
          content:
            application/json:
              schema:
                additionalProperties:
                  additionalProperties:
                    description: Array of predicates
                    items:
                      type: string
                    type: array
                  description: Target map
                  type: object
                description: Source map
                example:
                  chemical_substance:
                    gene:
                    - directly_interacts_with
                    - decreases_activity_of
                type: object
          description: Predicates by source and target
      summary: Get supported relationships by source and target
      tags:
      - predicates
      x-openapi-router-controller: openapi_server.controllers.predicates_controller
  /query:
    post:
      operationId: query
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
        description: Query information to be submitted
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: successful operation
        400:
          description: Invalid status value
      summary: Query reasoner via one of several inputs
      tags:
      - query
      x-swagger-router-controller: swagger_server.controllers.query_controller
      x-openapi-router-controller: openapi_server.controllers.query_controller
components:
  schemas:
    Query:
      additionalProperties: true
      properties:
        message:
          $ref: '#/components/schemas/Message'
      required:
      - message
      type: object
      x-body-name: request_body
    Message:
      additionalProperties: true
      example:
        knowledge_graph: '{}'
        results:
        - edge_bindings:
          - kg_id: ""
            qg_id: qg_id
          - kg_id: ""
            qg_id: qg_id
          node_bindings:
          - kg_id: ""
            qg_id: qg_id
          - kg_id: ""
            qg_id: qg_id
        - edge_bindings:
          - kg_id: ""
            qg_id: qg_id
          - kg_id: ""
            qg_id: qg_id
          node_bindings:
          - kg_id: ""
            qg_id: qg_id
          - kg_id: ""
            qg_id: qg_id
        query_graph:
          nodes:
          - curie: OMIM:603903
            id: n00
            type: ""
          - curie: OMIM:603903
            id: n00
            type: ""
          edges:
          - target_id: https://www.uniprot.org/uniprot/P00738
            id: e00
            source_id: https://omim.org/entry/603903
            type: ""
          - target_id: https://www.uniprot.org/uniprot/P00738
            id: e00
            source_id: https://omim.org/entry/603903
            type: ""
      properties:
        results:
          description: List of all returned potential answers for the query posed
          items:
            $ref: '#/components/schemas/Result'
          type: array
        query_graph:
          $ref: '#/components/schemas/QueryGraph'
        knowledge_graph:
          description: KnowledgeGraph object that contains all the nodes and edges referenced in any of the possible answers to the query OR connection information for a remote knowledge graph
          oneOf:
          - $ref: '#/components/schemas/KnowledgeGraph'
          - $ref: '#/components/schemas/RemoteKnowledgeGraph'
          type: object
      type: object
    Result:
      description: One of potentially several results or answers for a query
      example:
        edge_bindings:
        - kg_id: ""
          qg_id: qg_id
        - kg_id: ""
          qg_id: qg_id
        node_bindings:
        - kg_id: ""
          qg_id: qg_id
        - kg_id: ""
          qg_id: qg_id
      properties:
        node_bindings:
          description: List of QNode-KNode bindings.
          items:
            $ref: '#/components/schemas/NodeBinding'
          type: array
        edge_bindings:
          description: List of QEdge-KEdge bindings.
          items:
            $ref: '#/components/schemas/EdgeBinding'
          type: array
      required:
      - edge_bindings
      - node_bindings
      type: object
    NodeBinding:
      example:
        kg_id: ""
        qg_id: qg_id
      properties:
        qg_id:
          description: Query-graph node id, i.e. the `node_id` of a QNode
          type: string
        kg_id:
          description: One or more knowledge-graph node ids, i.e. the `id` of a KNode
          oneOf:
          - type: string
          - items:
              type: string
            type: array
      required:
      - kg_id
      - qg_id
      type: object
    EdgeBinding:
      example:
        kg_id: ""
        qg_id: qg_id
      properties:
        qg_id:
          description: Query-graph edge id, i.e. the `edge_id` of a QEdge
          type: string
        kg_id:
          description: One or more knowledge-graph edge ids, i.e. the `id` of a KEdge
          oneOf:
          - type: string
          - items:
              type: string
            type: array
      required:
      - kg_id
      - qg_id
      type: object
    KnowledgeGraph:
      additionalProperties: true
      description: A thought graph associated with this result. This will commonly be a linear path subgraph from one concept to another, but related items aside of the path may be included.
      properties:
        nodes:
          description: List of nodes in the KnowledgeGraph
          items:
            $ref: '#/components/schemas/Node'
          type: array
        edges:
          description: List of edges in the KnowledgeGraph
          items:
            $ref: '#/components/schemas/Edge'
          type: array
      required:
      - edges
      - nodes
      type: object
    RemoteKnowledgeGraph:
      description: A thought graph associated with this result that is not repeated here, but stored elsewhere in a way that can be remotely accessed by the reader of this Message
      properties:
        url:
          description: URL that provides programmatic access to the remote knowledge graph
          example: http://robokop.renci.org/api/kg
          type: string
        credentials:
          description: Credentials needed for programmatic access to the remote knowledge graph
          items:
            $ref: '#/components/schemas/Credentials'
          type: object
        protocol:
          default: neo4j
          type: string
      required:
      - url
      type: object
    Credentials:
      additionalProperties: true
      description: Credentials needed for programmatic access to the remote knowledge graph
      properties:
        username:
          description: Username needed for programmatic access to the remote knowledge graph
          type: string
        password:
          description: Password needed for programmatic access to the remote knowledge graph
          type: string
      required:
      - password
      - username
      type: object
    QueryGraph:
      additionalProperties: true
      description: A graph intended to be the thought path to be followed by a reasoner to answer the question. This graph is a representation of a question.
      example:
        nodes:
        - curie: OMIM:603903
          id: n00
          type: ""
        - curie: OMIM:603903
          id: n00
          type: ""
        edges:
        - target_id: https://www.uniprot.org/uniprot/P00738
          id: e00
          source_id: https://omim.org/entry/603903
          type: ""
        - target_id: https://www.uniprot.org/uniprot/P00738
          id: e00
          source_id: https://omim.org/entry/603903
          type: ""
      properties:
        nodes:
          description: List of nodes in the QueryGraph
          items:
            $ref: '#/components/schemas/QNode'
          type: array
        edges:
          description: List of edges in the QueryGraph
          items:
            $ref: '#/components/schemas/QEdge'
          type: array
      required:
      - edges
      - nodes
      type: object
    QNode:
      additionalProperties: true
      description: A node in the QueryGraph
      example:
        curie: OMIM:603903
        id: n00
        type: ""
      properties:
        id:
          description: 'QueryGraph internal identifier for this QNode. Recommended
            form: n00, n01, n02, etc.'
          example: n00
          type: string
        curie:
          description: CURIE identifier for this node
          example: OMIM:603903
          oneOf:
          - type: string
          - items:
              type: string
            type: array
        type:
          oneOf:
          - $ref: '#/components/schemas/BiolinkEntity'
          - items:
              $ref: '#/components/schemas/BiolinkEntity'
            type: array
      required:
      - id
      type: object
    QEdge:
      additionalProperties: true
      description: An edge in the QueryGraph
      example:
        target_id: https://www.uniprot.org/uniprot/P00738
        id: e00
        source_id: https://omim.org/entry/603903
        type: ""
      properties:
        id:
          description: 'QueryGraph internal identifier for this QEdge. Recommended
            form: e00, e01, e02, etc.'
          example: e00
          type: string
        type:
          oneOf:
          - $ref: '#/components/schemas/BiolinkRelation'
          - items:
              $ref: '#/components/schemas/BiolinkRelation'
            type: array
        source_id:
          description: Corresponds to the @id of source node of this edge
          example: https://omim.org/entry/603903
          type: string
        target_id:
          description: Corresponds to the @id of target node of this edge
          example: https://www.uniprot.org/uniprot/P00738
          type: string
      required:
      - id
      - source_id
      - target_id
      type: object
    Node:
      additionalProperties: true
      description: A node in the thought subgraph
      properties:
        id:
          description: CURIE identifier for this node
          example: OMIM:603903
          type: string
        name:
          description: Formal name of the entity
          example: Haptoglobin
          type: string
        type:
          oneOf:
          - type: string
          - items:
              $ref: '#/components/schemas/BiolinkEntity'
            type: array
      required:
      - id
      type: object
    Edge:
      additionalProperties: true
      description: An edge in the thought subgraph linking two nodes
      properties:
        id:
          description: Local identifier for this edge which is unique within this KnowledgeGraph, and perhaps within the source reasoner's knowledge graph
          example: "553903"
          type: string
        type:
          description: A relation, i.e. child of related_to (snake_case)
          example: affects
          externalDocs:
            description: Biolink model relations
            url: https://biolink.github.io/biolink-model/docs/related_to.html
          type: string
        source_id:
          description: Corresponds to the @id of source node of this edge
          example: https://omim.org/entry/603903
          type: string
        target_id:
          description: Corresponds to the @id of target node of this edge
          example: https://www.uniprot.org/uniprot/P00738
          type: string
      required:
      - id
      - source_id
      - target_id
      type: object
    BiolinkEntity:
      description: A subclass of category named_thing (snake_case)
      example: disease
      externalDocs:
        description: Biolink model entities
        url: https://biolink.github.io/biolink-model/docs/NamedThing.html
      type: string
    BiolinkRelation:
      description: A relation, i.e. child of related_to (snake_case)
      example: affects
      externalDocs:
        description: Biolink model relations
        url: https://biolink.github.io/biolink-model/docs/related_to.html
      type: string
